// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_SQLOLEDB_Test_2_H
#define WINRT_SQLOLEDB_Test_2_H
#include "winrt/impl/Microsoft.UI.Xaml.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.1.h"
#include "winrt/impl/SQLOLEDB_Test.1.h"
WINRT_EXPORT namespace winrt::SQLOLEDB_Test
{
    struct WINRT_IMPL_EMPTY_BASES MainWindow : winrt::SQLOLEDB_Test::IMainWindow,
        impl::base<MainWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<MainWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        MainWindow(std::nullptr_t) noexcept {}
        MainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::SQLOLEDB_Test::IMainWindow(ptr, take_ownership_from_abi) {}
        MainWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES PersonViewModel : winrt::SQLOLEDB_Test::IPersonViewModel
    {
        PersonViewModel(std::nullptr_t) noexcept {}
        PersonViewModel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::SQLOLEDB_Test::IPersonViewModel(ptr, take_ownership_from_abi) {}
        PersonViewModel();
    };
    struct WINRT_IMPL_EMPTY_BASES XamlMetaDataProvider : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
