// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_SQLOLEDB_Test_1_H
#define WINRT_SQLOLEDB_Test_1_H
#include "winrt/impl/SQLOLEDB_Test.0.h"
WINRT_EXPORT namespace winrt::SQLOLEDB_Test
{
    struct WINRT_IMPL_EMPTY_BASES IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPersonViewModel :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPersonViewModel>
    {
        IPersonViewModel(std::nullptr_t = nullptr) noexcept {}
        IPersonViewModel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
